# Generated by Django 4.2.25 on 2025-11-02 06:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="사용자 소개")),
                ("avatar", models.URLField(blank=True, help_text="프로필 이미지 URL")),
                (
                    "preferences",
                    models.JSONField(default=dict, help_text="사용자 설정"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="새로운 대화", help_text="대화 제목", max_length=255
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(auto_now=True, help_text="마지막 메시지 시각"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="대화 소유자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Intent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_input", models.TextField(help_text="원본 사용자 입력")),
                (
                    "cognitive_goal",
                    models.CharField(
                        choices=[
                            ("알기", "알기 - 정보 획득"),
                            ("하기", "하기 - 문제 해결"),
                            ("만들기", "만들기 - 생성/창작"),
                            ("배우기", "배우기 - 학습"),
                        ],
                        help_text="인지적 목표",
                        max_length=50,
                    ),
                ),
                (
                    "specificity",
                    models.CharField(
                        choices=[
                            ("LOW", "낮음 - 추상적"),
                            ("MEDIUM", "중간 - 범주적"),
                            ("HIGH", "높음 - 구체적"),
                        ],
                        help_text="구체성 수준",
                        max_length=20,
                    ),
                ),
                (
                    "completeness",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "불완전 - 정보 부족"),
                            ("PARTIAL", "부분적 - 일부 정보만"),
                            ("COMPLETE", "완전 - 충분한 정보"),
                        ],
                        help_text="완결성",
                        max_length=20,
                    ),
                ),
                (
                    "primary_entities",
                    models.JSONField(
                        default=list, help_text="핵심 엔티티/키워드 (리스트)"
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(default=list, help_text="제약조건 (리스트)"),
                ),
                ("confidence", models.FloatField(help_text="신뢰도 (0.0 - 1.0)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "intents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromptHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt_hash",
                    models.CharField(
                        db_index=True,
                        help_text="프롬프트 SHA256 해시 (캐싱용)",
                        max_length=64,
                    ),
                ),
                ("original_prompt", models.TextField(help_text="원본 프롬프트")),
                (
                    "synthesized_prompt",
                    models.TextField(help_text="합성/최적화된 프롬프트"),
                ),
                (
                    "model_used",
                    models.CharField(help_text="사용된 모델명", max_length=100),
                ),
                (
                    "provider",
                    models.CharField(
                        default="openai", help_text="LLM 제공자", max_length=50
                    ),
                ),
                ("response", models.TextField(help_text="LLM 응답")),
                (
                    "tokens_used",
                    models.IntegerField(default=0, help_text="사용된 토큰 수"),
                ),
                ("temperature", models.FloatField(default=0.7, help_text="생성 온도")),
                (
                    "quality_level",
                    models.CharField(
                        default="balanced",
                        help_text="품질 수준 (low/balanced/high)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "prompt_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCustomInstructions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instructions", models.TextField(help_text="커스텀 지침 내용")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_instructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Custom Instructions",
                "db_table": "user_custom_instructions",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        default="당신은 전문 AI 어시스턴트입니다.",
                        help_text="AI의 역할 정의",
                    ),
                ),
                ("task", models.TextField(blank=True, help_text="수행할 작업 명세")),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="대화 컨텍스트 (딕셔너리)"
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(default=list, help_text="제약 조건 (리스트)"),
                ),
                (
                    "user_preferences",
                    models.JSONField(default=dict, help_text="학습된 사용자 선호도"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="연관 대화",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="세션 소유자 (익명 사용자는 null)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(help_text="참고자료 URL", max_length=500)),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="참고자료 제목", max_length=500
                    ),
                ),
                (
                    "snippet",
                    models.TextField(blank=True, help_text="참고자료 요약/발췌"),
                ),
                (
                    "source",
                    models.CharField(
                        default="perplexity", help_text="검색 소스", max_length=100
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, help_text="관련성 점수"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt_history",
                    models.ForeignKey(
                        help_text="연관 프롬프트 이력",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_references",
                        to="core.prompthistory",
                    ),
                ),
            ],
            options={
                "db_table": "search_references",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(help_text="질문 내용")),
                (
                    "priority",
                    models.IntegerField(
                        default=3, help_text="우선순위 (1=최고, 5=최저)"
                    ),
                ),
                ("rationale", models.TextField(help_text="왜 이 질문이 필요한가")),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text="선택지 (리스트)"
                    ),
                ),
                ("default_value", models.TextField(blank=True, help_text="기본값")),
                ("user_answer", models.TextField(blank=True, help_text="사용자 답변")),
                (
                    "answered_at",
                    models.DateTimeField(blank=True, help_text="답변 시각", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intent",
                    models.ForeignKey(
                        help_text="연관된 Intent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="core.intent",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="prompthistory",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="연관된 세션",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prompt_history",
                to="core.session",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("assistant", "AI 어시스턴트"),
                            ("system", "시스템"),
                        ],
                        help_text="메시지 역할",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="메시지 내용")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="메타데이터 (토큰 수, 모델 등)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="소속 대화",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="intent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="연관된 세션",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intents",
                to="core.session",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feedback_text", models.TextField(help_text="피드백 내용")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "긍정"),
                            ("neutral", "중립"),
                            ("negative", "부정"),
                        ],
                        default="neutral",
                        help_text="감정 분류",
                        max_length=20,
                    ),
                ),
                (
                    "applied_adjustments",
                    models.JSONField(
                        default=list, help_text="적용된 조정사항 (리스트)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt_history",
                    models.ForeignKey(
                        blank=True,
                        help_text="연관된 프롬프트 이력",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.prompthistory",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="연관된 세션",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "db_table": "feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="임베딩할 내용")),
                (
                    "embedding_vector",
                    models.BinaryField(
                        help_text="임베딩 벡터 (numpy array를 bytes로 저장)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="메타데이터 (토큰 수, 임베딩 모델 등)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="연관 대화",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="core.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="연관 메시지",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="core.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversation_memories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["-created_at"], name="sessions_created_eb29b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "-created_at"], name="sessions_user_id_06dff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchreference",
            index=models.Index(
                fields=["prompt_history", "-relevance_score"],
                name="search_refe_prompt__e74e5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["intent", "priority"], name="questions_intent__9adb0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["prompt_hash"], name="prompt_hist_prompt__ecf1ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["-created_at"], name="prompt_hist_created_019038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["session", "-created_at"], name="prompt_hist_session_b5b3fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prompthistory",
            index=models.Index(
                fields=["model_used"], name="prompt_hist_model_u_d0629a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="messages_convers_3ebb41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["role"], name="messages_role_8be1df_idx"),
        ),
        migrations.AddIndex(
            model_name="intent",
            index=models.Index(
                fields=["-created_at"], name="intents_created_f51872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intent",
            index=models.Index(
                fields=["session", "-created_at"], name="intents_session_c65ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intent",
            index=models.Index(
                fields=["confidence"], name="intents_confide_e38289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["session", "-created_at"], name="feedbacks_session_f3df21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["sentiment"], name="feedbacks_sentime_c455ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmemory",
            index=models.Index(
                fields=["user", "-created_at"], name="conversatio_user_id_3c8770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationmemory",
            index=models.Index(
                fields=["conversation"], name="conversatio_convers_eb3d1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-last_message_at"],
                name="conversatio_user_id_22c68a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-created_at"], name="conversatio_created_d82801_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
    ]
