# Generated by Django 4.2.25 on 2025-11-02 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="초대 코드", max_length=20, unique=True
                    ),
                ),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, help_text="사용 일시", null=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="만료일 (선택적)", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invite_codes",
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("deposit_confirmed", "입금 완료 신청"),
                            ("approved", "승인됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        help_text="결제 상태",
                        max_length=20,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, help_text="요청 일시"),
                ),
                (
                    "deposit_confirmed",
                    models.BooleanField(
                        default=False, help_text="입금 완료 여부 (사용자가 체크)"
                    ),
                ),
                (
                    "deposit_confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="입금 완료 신청 일시", null=True
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, help_text="관리자 승인 여부"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, help_text="승인 일시", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="관리자 메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="플랜 이름 (free, basic, pro)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="플랜 표시 이름", max_length=100),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("free", "무료"), ("basic", "Basic"), ("pro", "Pro")],
                        help_text="플랜 유형",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="월 가격 (USD)",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_limit",
                    models.BigIntegerField(help_text="월 사용량 제한 (토큰 수)"),
                ),
                (
                    "allowed_models",
                    models.JSONField(
                        default=list,
                        help_text="허용된 모델 리스트 (예: ['gpt-5-nano', 'gpt-5-mini'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                ("description", models.TextField(blank=True, help_text="플랜 설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="구독 활성화 여부"),
                ),
                (
                    "current_usage",
                    models.BigIntegerField(
                        default=0, help_text="현재 월 사용량 (토큰 수)"
                    ),
                ),
                (
                    "bonus_tokens",
                    models.BigIntegerField(
                        default=0, help_text="보너스 토큰 (친구 초대 등)"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="구독 시작일", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="구독 종료일", null=True
                    ),
                ),
                (
                    "last_reset_date",
                    models.DateTimeField(
                        blank=True, help_text="마지막 사용량 리셋 일시", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="구독 플랜",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to="core.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="구독 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(help_text="연도")),
                ("month", models.IntegerField(help_text="월 (1-12)")),
                (
                    "total_tokens",
                    models.BigIntegerField(default=0, help_text="총 사용 토큰 수"),
                ),
                (
                    "tokens_by_model",
                    models.JSONField(
                        default=dict,
                        help_text="모델별 사용 토큰 수 (예: {'gpt-5-nano': 100000, 'gpt-5-mini': 50000})",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="연관 구독",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.usersubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usage_records",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["plan_type"], name="subscriptio_plan_ty_9c7ad6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="승인한 관리자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="plan",
            field=models.ForeignKey(
                help_text="구독 플랜",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to="core.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="user",
            field=models.ForeignKey(
                help_text="결제 요청 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitecode",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                help_text="초대받은 사용자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_invite_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitecode",
            name="inviter",
            field=models.ForeignKey(
                help_text="초대한 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invite_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["user", "-start_date"], name="user_subscr_user_id_2a4e70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["is_active"], name="user_subscr_is_acti_237b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["user", "-year", "-month"],
                name="usage_recor_user_id_ede0c1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usagerecord",
            unique_together={("user", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["user", "-requested_at"], name="payment_req_user_id_63241d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(fields=["status"], name="payment_req_status_65728f_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["-requested_at"], name="payment_req_request_750081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(fields=["code"], name="invite_code_code_bdf127_idx"),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(
                fields=["inviter", "-created_at"], name="invite_code_inviter_4f65e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitecode",
            index=models.Index(
                fields=["is_used"], name="invite_code_is_used_ecde9a_idx"
            ),
        ),
    ]
