# Generated by Django 4.2.25 on 2025-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_invitecode_paymentrequest_subscriptionplan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                help_text="이메일 인증 토큰",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, help_text="이메일 인증 완료 여부"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_token_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="인증 토큰 만료 시각", null=True
            ),
        ),
    ]
